from flask import Flask, request, send_file, jsonify
from flask_cors import CORS
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
import yt_dlp
import io
import os
import time
import subprocess
import json
import tempfile
import atexit
import urllib.parse
import shutil
import uuid
from datetime import timedelta

app = Flask(__name__)

# Restrict CORS to the extension origin only
CORS(app, origins=[
    'chrome-extension://*',
    'https://takevid-server.onrender.com'
])

# Rate Limiting
limiter = Limiter(
    app=app,
    key_func=get_remote_address,
    default_limits=["60 per minute"],
    storage_uri="memory://"
)

# URL Validation
ALLOWED_DOMAINS = ['youtube.com', 'youtu.be', 'tiktok.com', 'facebook.com', 'fb.watch', 'instagram.com']

def is_valid_url(url):
    """Validate URL to prevent SSRF attacks."""
    try:
        parsed = urllib.parse.urlparse(url)
        if parsed.scheme not in ['http', 'https']:
            return False
        hostname = parsed.hostname.lower() if parsed.hostname else ''
        return any(hostname == d or hostname.endswith('.' + d) for d in ALLOWED_DOMAINS)
    except (ValueError, AttributeError):
        return False

# --- Configuration ---
YT_DLP_PATH = shutil.which('yt-dlp') or 'yt-dlp'

def check_yt_dlp():
    """Verify that yt-dlp is accessible."""
    try:
        result = subprocess.run([YT_DLP_PATH, '--version'], capture_output=True, text=True, check=True)
        print(f"yt-dlp version verified: {result.stdout.strip()}")
        return True
    except (subprocess.CalledProcessError, FileNotFoundError, OSError) as e:
        print(f"CRITICAL: yt-dlp not found or error executing. Path: {YT_DLP_PATH}. Error: {e}")
        return False

check_yt_dlp()

def _create_cookie_file(cookies_list):
    if not cookies_list:
        return None
    
    temp_fd, path = tempfile.mkstemp(suffix='.txt')
    try:
        with os.fdopen(temp_fd, 'w', encoding='utf-8') as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by TakeVid\n")
            for c in cookies_list:
                domain = c.get('domain', '')
                if not domain:
                    continue
                
                flag = "TRUE" if domain.startswith('.') else "FALSE"
                path_str = c.get('path', '/')
                secure = "TRUE" if c.get('secure', False) else "FALSE"
                expiry = int(c.get('expirationDate', time.time() + 86400))
                name = c.get('name', '')
                value = c.get('value', '')
                
                f.write(f"{domain}\t{flag}\t{path_str}\t{secure}\t{expiry}\t{name}\t{value}\n")
        return path
    except (IOError, OSError) as e:
        print(f"Error creating cookie file: {e}")
        try:
            os.close(temp_fd)
        except OSError:
            pass
        return None

def _cleanup_temp_files(base_name, cookie_path=None):
    """Clean up all temp files matching the base name, including subtitle files."""
    try:
        for file in os.listdir('.'):
            if file.startswith(base_name):
                try:
                    os.remove(file)
                except OSError:
                    pass
        if cookie_path and os.path.exists(cookie_path):
            try:
                os.remove(cookie_path)
            except OSError:
                pass
    except OSError:
        pass

@app.route('/')
def home():
    yt_version = "Unknown"
    try:
        result = subprocess.run([YT_DLP_PATH, '--version'], capture_output=True, text=True)
        yt_version = result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError) as e:
        yt_version = f"Error: {e}"
    
    return jsonify({
        'status': 'running',
        'yt_dlp_path': YT_DLP_PATH,
        'yt_dlp_version': yt_version
    })

def get_video_info(url, cookie_path=None, user_agent=None):
    """Fallback to CLI for robust extraction if library fails to see all formats"""
    is_youtube = 'youtube.com' in url or 'youtu.be' in url
    
    client_configs = [
        {'clients': 'web', 'ua': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'},
        {'clients': 'mweb', 'ua': 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36'},
        {'clients': 'android', 'ua': 'com.google.android.youtube/19.07.39 (Linux; U; Android 14) gzip'}
    ] if is_youtube else [{'clients': None, 'ua': user_agent}]

    last_error = None
    for config in client_configs:
        try:
            cmd = [
                YT_DLP_PATH, 
                '--no-playlist', 
                '--dump-json', 
                '--no-check-certificate',
                '--no-warnings',
                '--geo-bypass',
                '--ignore-errors',
                '--no-check-formats',
            ]

            if is_youtube:
                cmd.extend(['--extractor-args', f'youtube:player-client={config["clients"]}'])
                ua = config['ua']
            else:
                ua = config['ua'] or 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'
                cmd.extend(['--add-header', 'Referer:https://www.tiktok.com/'])
                cmd.extend(['--add-header', 'Origin:https://www.tiktok.com/'])

            cmd.extend(['--user-agent', ua])
            cmd.extend(['--add-header', 'Accept: */*'])
            cmd.extend(['--add-header', 'Accept-Language: en-US,en;q=0.9'])
            
            if cookie_path:
                 cmd.extend(['--cookies', cookie_path])
            
            cmd.append(url)

            result = subprocess.run(cmd, capture_output=True, text=True, check=True, encoding='utf-8', timeout=90)
            
            if result.stdout.strip():
                return json.loads(result.stdout)
                
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired, json.JSONDecodeError, OSError) as e:
            last_error = str(e)
            if hasattr(e, 'stderr'):
                last_error += f" | {e.stderr}"
            continue

    error_msg = last_error or "Unknown error during extraction"
    if "Sign in to confirm you're not a bot" in error_msg:
        return {'error': "YouTube is being extra protective today. Try logging out and back in on YouTube, then refreshing this page."}
    return {'error': f"Extraction failed: {error_msg[:200]}"}

@app.route('/analyze', methods=['POST'])
@limiter.limit("20 per minute")
def analyze():
    data = request.json
    if not data:
        return jsonify({'error': 'No data provided'}), 400
    
    url = data.get('url')
    cookies_list = data.get('cookies')
    user_agent = data.get('userAgent')
    
    if not url:
        return jsonify({'error': 'No URL provided'}), 400
    
    if not is_valid_url(url):
        return jsonify({'error': 'Invalid URL. Only YouTube, TikTok, Facebook, Instagram supported.'}), 400

    cookie_path = _create_cookie_file(cookies_list)

    try:
        info = get_video_info(url, cookie_path, user_agent)
    finally:
        if cookie_path and os.path.exists(cookie_path):
            try:
                os.remove(cookie_path)
            except OSError:
                pass

    if not info:
        return jsonify({'error': 'Could not extract video info (Unknown Error)'}), 500
        
    if 'error' in info:
         return jsonify({'error': info['error']}), 500

    formats_list = info.get('formats', [])
    processed_formats = {}
    target_resolutions = ['2160p', '1440p', '1080p', '720p', '480p', '360p']
    
    for f in formats_list:
        if f.get('vcodec') == 'none':
            continue
        
        height = f.get('height')
        width = f.get('width')
        
        if height:
            compare_dim = height
            is_vertical = False
            if width and height > width:
                compare_dim = width
                is_vertical = True
            
            if compare_dim >= 2160: res = '2160p'
            elif compare_dim >= 1440: res = '1440p'
            elif compare_dim >= 1080: res = '1080p'
            elif compare_dim >= 720: res = '720p'
            elif compare_dim >= 480: res = '480p'
            elif compare_dim >= 360: res = '360p'
            else: res = 'low'
        else:
             continue

        if res in target_resolutions:
            size = f.get('filesize') or f.get('filesize_approx') or 0
            ext = f.get('ext')
            
            if res not in processed_formats:
                processed_formats[res] = {
                    'resolution': res,
                    'size': size,
                    'format_id': f['format_id'],
                    'ext': ext,
                    'height': height,
                    'is_vertical': is_vertical
                }
            else:
                curr_val = processed_formats[res]
                if curr_val['ext'] != 'mp4' and ext == 'mp4':
                     processed_formats[res] = {
                        'resolution': res,
                        'size': size,
                        'format_id': f['format_id'],
                        'ext': ext,
                        'height': height,
                        'is_vertical': is_vertical
                    }
                elif curr_val['ext'] == ext and size > curr_val['size']:
                    processed_formats[res] = {
                        'resolution': res,
                        'size': size,
                        'format_id': f['format_id'],
                        'ext': ext,
                        'height': height,
                        'is_vertical': is_vertical
                    }

    audio_size = 0
    for f in formats_list:
        if f.get('vcodec') == 'none' and f.get('acodec') != 'none':
             s = f.get('filesize') or f.get('filesize_approx') or 0
             if s > audio_size:
                 audio_size = s

    final_formats = []
    for res in target_resolutions:
        if res in processed_formats:
            fmt = processed_formats[res]
            total_size = fmt['size'] + audio_size 
            
            display_quality = res
            if fmt.get('is_vertical'):
                display_quality += ' (Vertical)'
            
            final_formats.append({
                'id': fmt['format_id'],
                'type': 'video',
                'quality': display_quality,
                'height': fmt['height'],
                'size_bytes': total_size,
                'size_text': f"{total_size / (1024*1024):.1f} MB" if total_size > 0 else "Estimate"
            })
    
    final_formats.append({
        'id': 'bestaudio',
        'type': 'audio',
        'quality': '128kbps',
        'size_bytes': audio_size,
        'size_text': f"{audio_size / (1024*1024):.1f} MB" if audio_size > 0 else "Estimate"
    })

    return jsonify({
        'title': info.get('title'),
        'thumbnail': info.get('thumbnail'),
        'duration': info.get('duration'),
        'webpage_url': info.get('webpage_url'),
        'uploader': info.get('uploader'),
        'formats': final_formats
    })


# Redis connection for multi-worker compatibility
try:
    import redis
    redis_client = redis.Redis(
        host=os.environ.get('REDIS_HOST', 'localhost'),
        port=int(os.environ.get('REDIS_PORT', 6379)),
        password=os.environ.get('REDIS_PASSWORD', None),
        decode_responses=True,
        socket_connect_timeout=2
    )
    redis_client.ping()
    USE_REDIS = True
    print("Redis connected successfully for multi-worker support")
except Exception as e:
    print(f"Redis not available, using in-memory storage (single worker only): {e}")
    USE_REDIS = False
    download_requests = {}

@app.route('/prepare_download', methods=['POST'])
@limiter.limit("10 per minute")
def prepare_download():
    """Stores download parameters and returns a token for GET access."""
    try:
        data = request.json
        if not data or not data.get('url'):
            return jsonify({'error': 'No URL provided'}), 400
        
        if not is_valid_url(data.get('url')):
            return jsonify({'error': 'Invalid URL'}), 400
            
        token = str(uuid.uuid4())
        data_to_store = {
            'url': data.get('url'),
            'format': data.get('format'),
            'quality': data.get('quality'),
            'format_id': data.get('format_id'),
            'cookies': data.get('cookies'),
            'user_agent': data.get('userAgent'),
            'timestamp': time.time()
        }
        
        if USE_REDIS:
            redis_client.setex(
                f"download:{token}",
                timedelta(minutes=5),
                json.dumps(data_to_store)
            )
        else:
            download_requests[token] = data_to_store
            
            # Cleanup old tokens
            current_time = time.time()
            to_delete = [k for k, v in download_requests.items() if current_time - v['timestamp'] > 300]
            for k in to_delete:
                del download_requests[k]
            
        return jsonify({'token': token})
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/trigger_download/<token>', methods=['GET'])
@limiter.limit("10 per minute")
def trigger_download(token):
    """Executes the download using stored parameters."""
    try:
        if USE_REDIS:
            data_str = redis_client.get(f"download:{token}")
            if not data_str:
                return jsonify({'error': 'Invalid or expired download token'}), 404
            req_data = json.loads(data_str)
            redis_client.delete(f"download:{token}")
        else:
            req_data = download_requests.get(token)
            if not req_data:
                return jsonify({'error': 'Invalid or expired download token'}), 404
            del download_requests[token]
    except Exception as e:
        return jsonify({'error': f'Token retrieval error: {str(e)}'}), 500

    url = req_data.get('url')
    fmt_type = req_data.get('format')
    quality = req_data.get('quality')
    format_id = req_data.get('format_id')
    cookies_list = req_data.get('cookies')
    auto_subtitles = req_data.get('auto_subtitles', True)

    if not is_valid_url(url):
        return jsonify({'error': 'Invalid URL'}), 400

    cookie_path = _create_cookie_file(cookies_list)

    yt_dlp_exe = YT_DLP_PATH

    if fmt_type == 'audio':
        format_str = 'bestaudio/best'
    elif format_id and format_id != 'bestaudio':
        # Use format_id if available, but provide fallbacks for SABR compatibility
        format_str = f'{format_id}+bestaudio/best'
    elif quality:
        targets = [144, 240, 360, 480, 720, 1080, 1440, 2160]
        q_clean = str(quality).replace('p', '')
        if q_clean.isdigit() and int(q_clean) in targets:
            format_str = f'bestvideo[height<={q_clean}]+bestaudio/bestvideo[height<={q_clean}]+bestaudio/best'
        else:
            format_str = f'{quality}+bestaudio/best'
    else:
        # Default: let yt-dlp pick best compatible format
        format_str = 'bestvideo*+bestaudio/bestvideo+bestaudio/best'

    timestamp = int(time.time())
    temp_filename = f"temp_{timestamp}"

    is_youtube = 'youtube.com' in url or 'youtu.be' in url

    try:
        clients_to_try = ['android', 'web', 'mweb'] if is_youtube else [None]
        last_error = None
        downloaded_file = None
        last_error_msg = None

        for client in clients_to_try:
            try:
                cmd = [
                    yt_dlp_exe,
                    '--no-playlist',
                    '--format', format_str,
                    '--merge-output-format', 'mp4',
                    '-o', f'{temp_filename}.%(ext)s',
                    '--no-warnings',
                    '--no-check-certificate',
                    '--prefer-free-formats',
                    '--ignore-errors',
                ]

                if is_youtube:
                    # Try android first - better for SABR streaming
                    if client == 'android':
                        cmd.extend(['--extractor-args', 'youtube:player-client=android'])
                        ua = 'com.google.android.youtube/19.07.39 (Linux; U; Android 14) gzip'
                    elif client == 'mweb':
                        cmd.extend(['--extractor-args', 'youtube:player-client=mweb'])
                        ua = 'Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36'
                    else:
                        cmd.extend(['--extractor-args', 'youtube:player-client=web'])
                        ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'

                    cmd.extend(['--socket-timeout', '30'])
                    cmd.extend(['--retries', '3'])
                else:
                    ua = req_data.get('user_agent') or 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36'

                cmd.extend(['--user-agent', ua])

                if cookie_path:
                    cmd.extend(['--cookies', cookie_path])

                # Subtitle support (controlled by settings)
                if auto_subtitles:
                    cmd.extend([
                        '--write-subs',
                        '--write-auto-subs',
                        '--sub-langs', 'en,ar,es,fr,de,it,pt,ru,ja,ko,zh',
                        '--embed-subs',
                        '--convert-subs', 'srt'
                    ])

                if fmt_type == 'audio':
                    cmd.extend(['-x', '--audio-format', 'mp3'])

                cmd.append(url)

                result = subprocess.run(cmd, check=True, capture_output=True, text=True, encoding='utf-8', timeout=300)

                for file in os.listdir('.'):
                    if file.startswith(temp_filename) and not file.endswith('.part'):
                        if not file.endswith(('.srt', '.vtt', '.ass')):
                            downloaded_file = file
                            break

                if downloaded_file:
                    break

            except (subprocess.CalledProcessError, subprocess.TimeoutExpired, OSError) as e:
                last_error = e
                if hasattr(e, 'stderr') and e.stderr:
                    last_error_msg = e.stderr
                elif hasattr(e, 'stdout') and e.stdout:
                    last_error_msg = e.stdout
                continue

        if not downloaded_file:
            # If specific format failed, try again with general best format
            if format_id and format_id != 'bestaudio':
                print(f"Specific format {format_id} failed, retrying with best format...")
                fallback_format = 'bestvideo*+bestaudio/bestvideo+bestaudio/best'

                try:
                    cmd = [
                        yt_dlp_exe,
                        '--no-playlist',
                        '--format', fallback_format,
                        '--merge-output-format', 'mp4',
                        '-o', f'{temp_filename}.%(ext)s',
                        '--no-warnings',
                        '--no-check-certificate',
                        '--prefer-free-formats',
                        '--retries', '3',
                    ]

                    if is_youtube:
                        cmd.extend(['--extractor-args', 'youtube:player-client=android'])
                        cmd.extend(['--socket-timeout', '30'])

                    if cookie_path:
                        cmd.extend(['--cookies', cookie_path])

                    if fmt_type == 'audio':
                        cmd.extend(['-x', '--audio-format', 'mp3'])

                    cmd.append(url)

                    subprocess.run(cmd, check=True, capture_output=True, text=True, encoding='utf-8', timeout=300)

                    for file in os.listdir('.'):
                        if file.startswith(temp_filename) and not file.endswith('.part'):
                            if not file.endswith(('.srt', '.vtt', '.ass')):
                                downloaded_file = file
                                break

                except Exception as fallback_error:
                    print(f"Fallback download also failed: {fallback_error}")

            if not downloaded_file:
                _cleanup_temp_files(temp_filename, cookie_path)

                error_msg = last_error_msg if last_error_msg else (str(last_error) if last_error else "Unknown error - no file downloaded")

                # Extract useful error message
                if "requested format is not available" in error_msg.lower():
                    error_msg = "This video format is not available. Try selecting a different quality."
                elif "sign in to confirm" in error_msg.lower():
                    error_msg = "YouTube requires sign-in. Try enabling cookie sending in settings."

                return jsonify({'error': f"Download failed: {error_msg[:300]}"}), 500

        return_filename = f"video_{timestamp}.{'mp3' if fmt_type == 'audio' else 'mp4'}"

        response = send_file(
            downloaded_file,
            as_attachment=True,
            download_name=return_filename,
            mimetype='audio/mpeg' if fmt_type == 'audio' else 'video/mp4'
        )

        @response.call_on_close
        def cleanup_files():
            _cleanup_temp_files(temp_filename, cookie_path)

        return response

    except Exception as e:
        _cleanup_temp_files(temp_filename, cookie_path)
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
